### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by laxhya-godara** [TDanks2000/StreamAble#33]
Make a discord server for this app or make a telegram server for discussion and faq

**Comment by TDanks2000** [comment]
> Make a discord server for this app or make a telegram server for discussion and faq

i have one it just isnt public rn

**Comment by laxhya-godara** [comment]
> > Make a discord server for this app or make a telegram server for discussion and faq
> 
> i have one it just isnt public rn

Can you provide any sort of invitation link to me ?
I want help with settings.....have you not added them and i can't seem to find manga section?

**Comment by TDanks2000** [comment]
> > > Make a discord server for this app or make a telegram server for discussion and faq
> > 
> > 
> > i have one it just isnt public rn
> 
> Can you provide any sort of invitation link to me ? I want help with settings.....have you not added them and i can't seem to find manga section?
there is not a manga section on the site

**Comment by laxhya-godara** [comment]
so you can't ?

**Comment by TDanks2000** [comment]
https://discord.gg/jm6GArH3QE
